spring:

  config:
    import:
      optional:file:.env[.properties]

  datasource:
    url: jdbc:h2:file:./assistant_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:

    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.yml